"""Agent 5 — Ranking (LangGraph node).

Three-axis scoring (saju / preference / distance) with fixed weights
(0.5 / 0.3 / 0.2). The reason text is generated by Solar with the score
breakdown so each rationale actually mentions the user's elements.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Tuple

from langgraph.config import get_stream_writer

from _lib.bazi import ELEMENT_TRAVEL_AFFINITY
from _lib.destinations import CandidateDestination
from _lib.solar import ChatMessage, SolarOptions, call_solar_json
from _lib.state import AgentState, make_event
from _lib.travel_styles import TRAVEL_STYLES

logger = logging.getLogger(__name__)

WEIGHT_SAJU = 0.5
WEIGHT_PREFERENCE = 0.3
WEIGHT_DISTANCE = 0.2

RANGE_LIMITS: Dict[str, float] = {
    "2시간 이내": 2.0,
    "4시간 이내": 4.0,
    "제한 없음": 8.0,
}

SYSTEM_PROMPT = """당신은 사주 명리학에 기반한 여행 큐레이터입니다.
각 여행지에 대해 왜 이 사용자에게 어울리는지 한국어 1~2문장으로 설명하세요.
규칙:
- 반드시 사용자의 부족한 오행(보완 필요)을 한 번 이상 언급하고, 어떤 환경 요소가 그 오행을 보완하는지 연결합니다.
- 선호 스타일이 있다면 어떻게 결합되는지도 자연스럽게 녹이세요.
- "재미·참고용" 어조를 유지하고 단정하지 마세요.
- 출력은 반드시 단일 JSON 객체로 합니다. {"reasons":[{"id":"...","reason":"..."}]}"""


def _clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def _round1(v: float) -> float:
    return round(v * 10) / 10


def _compute_saju_score(d: CandidateDestination, saju: Dict[str, Any]) -> float:
    s = 0.0
    if saju["needsBoost"] in d["elementAffinity"]:
        s += 60
    for el in saju["elements"]["strong"]:
        if el == saju["needsBoost"]:
            continue
        if el in d["elementAffinity"]:
            s += 8
    if saju["chart"]["dayMaster"]["element"] in d["elementAffinity"]:
        s += 12
    only_dominant = (
        len(d["elementAffinity"]) > 0
        and all(e == saju["elements"]["dominant"] for e in d["elementAffinity"])
        and saju["needsBoost"] not in d["elementAffinity"]
    )
    if only_dominant:
        s -= 20
    return _clamp(s, 0, 100)


def _compute_preference_score(
    d: CandidateDestination,
    user_input: Dict[str, Any],
    mapping: Dict[str, Any],
) -> float:
    s = 0.0
    user_styles = set(user_input["preferredStyles"])
    s += sum(1 for t in d["tags"] if t in user_styles) * 18
    preferred = set(mapping["preferredTags"])
    s += sum(1 for t in d["tags"] if t in preferred) * 8
    if mapping["primary"] in d["styles"]:
        s += 20
    if mapping["secondary"] and mapping["secondary"] in d["styles"]:
        s += 10
    avoid = set(mapping["avoidTags"])
    s -= sum(1 for t in d["tags"] if t in avoid) * 6
    return _clamp(s, 0, 100)


def _compute_distance_score(
    d: CandidateDestination, user_input: Dict[str, Any]
) -> float:
    t = d["travelTime"][user_input["departure"]]
    limit = RANGE_LIMITS[user_input["travelRange"]]
    if t > limit:
        return 0.0
    ratio = 1.0 - t / max(limit, 1.0)
    s = 50.0 + ratio * 50.0
    if user_input["travelDuration"] == "당일" and t <= 2:
        s += 5
    return _clamp(s, 0, 100)


def _fallback_reason(
    d: CandidateDestination, saju: Dict[str, Any], mapping: Dict[str, Any]
) -> str:
    env = ELEMENT_TRAVEL_AFFINITY[saju["needsBoost"]]["environments"][0]
    style_label = TRAVEL_STYLES[mapping["primary"]]["label"]
    return (
        f"{saju['needsBoost']}({saju['needsBoost']}) 기운이 부족한 지금, "
        f"{d['name']}의 {env} 결이 균형을 맞춰 줍니다. {style_label}의 흐름과도 "
        "자연스럽게 이어져요."
    )


async def _fetch_reasons(
    top: List[Tuple[CandidateDestination, Dict[str, float]]],
    user_input: Dict[str, Any],
    saju: Dict[str, Any],
    mapping: Dict[str, Any],
    api_key: str,
    model: str | None,
) -> Dict[str, str]:
    needs_boost = saju["needsBoost"]
    env_str = "/".join(ELEMENT_TRAVEL_AFFINITY[needs_boost]["environments"])
    strong_str = ", ".join(saju["elements"]["strong"]) or "뚜렷하지 않음"
    primary_label = TRAVEL_STYLES[mapping["primary"]]["label"]
    style_str = (
        f"{primary_label} + {TRAVEL_STYLES[mapping['secondary']]['label']}"
        if mapping["secondary"] else primary_label
    )
    preferred_str = ", ".join(user_input["preferredStyles"]) or "없음"

    lines: List[str] = [
        f"일간: {saju['chart']['dayMaster']['stem']}({saju['chart']['dayMaster']['element']})",
        f"보완 필요한 오행: {needs_boost} ({env_str} 같은 환경이 도움)",
        f"강한 오행: {strong_str}",
        f"매핑된 스타일: {style_str}",
        f"사용자 선호 태그: {preferred_str}",
        "",
        "아래 각 여행지에 대한 추천 이유를 1~2문장씩 작성해 주세요. 사주 보완 오행을 반드시 언급하세요.",
    ]
    for i, (d, b) in enumerate(top):
        tags_str = ", ".join(d["tags"])
        lines.append(
            f"{i + 1}. id={d['id']} | {d['name']}({d['region']}) | 태그: {tags_str} | "
            f"사주점수: {b['saju']} / 선호: {b['preference']} / 거리: {b['distance']}"
        )
    lines.append("")
    lines.append('JSON 형식: {"reasons":[{"id":"<id>","reason":"<문장>"}, ...]}')

    user_prompt = "\n".join(lines)

    try:
        res = await call_solar_json(
            [
                ChatMessage(role="system", content=SYSTEM_PROMPT),
                ChatMessage(role="user", content=user_prompt),
            ],
            SolarOptions(api_key=api_key, model=model, temperature=0.5, max_tokens=700),
        )
        out: Dict[str, str] = {}
        if isinstance(res, dict):
            for r in res.get("reasons") or []:
                if isinstance(r, dict) and r.get("id") and r.get("reason"):
                    out[r["id"]] = r["reason"]
        return out
    except Exception as err:  # noqa: BLE001
        logger.warning("[ranking] Solar fallback for reasons: %s", err)
        return {}


async def ranking_node(state: AgentState) -> Dict[str, Any]:
    writer = get_stream_writer()
    writer(make_event(
        "agent_start", agent="ranking", index=4, total=6,
    ))

    user_input = state["userInput"]
    saju = state["saju"]
    mapping = state["mapping"]
    candidates = state["candidates"]
    api_key = state["apiKey"]
    model = state.get("model")

    scored: List[Tuple[CandidateDestination, Dict[str, float]]] = []
    for d in candidates:
        saju_score = _compute_saju_score(d, saju)
        pref_score = _compute_preference_score(d, user_input, mapping)
        dist_score = _compute_distance_score(d, user_input)
        total = (
            saju_score * WEIGHT_SAJU
            + pref_score * WEIGHT_PREFERENCE
            + dist_score * WEIGHT_DISTANCE
        )
        scored.append((d, {
            "saju": _round1(saju_score),
            "preference": _round1(pref_score),
            "distance": _round1(dist_score),
            "total": _round1(total),
        }))

    scored.sort(key=lambda x: x[1]["total"], reverse=True)
    top3 = scored[:3]

    reason_map = await _fetch_reasons(top3, user_input, saju, mapping, api_key, model)

    ranked: List[Dict[str, Any]] = []
    for d, breakdown in top3:
        ranked.append({
            "destination": d,
            "score": breakdown,
            "reason": reason_map.get(d["id"]) or _fallback_reason(d, saju, mapping),
        })

    writer(make_event(
        "agent_done", agent="ranking", index=4, total=6,
        payload=[
            {"id": r["destination"]["id"], "name": r["destination"]["name"], "score": r["score"]}
            for r in ranked
        ],
    ))

    return {"ranked": ranked}
